import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

import '../../domain/entities/weather_observation.dart';
import '../bloc/weather_entry_bloc.dart';
import '../bloc/weather_entry_event.dart';
import '../bloc/weather_entry_state.dart';

class WeatherEntryPage extends StatefulWidget {
  const WeatherEntryPage({super.key});

  @override
  State<WeatherEntryPage> createState() => _WeatherEntryPageState();
}

class _WeatherEntryPageState extends State<WeatherEntryPage> {
  final _formKey = GlobalKey<FormState>();
  final _tempController = TextEditingController();
  final _rainController = TextEditingController();
  final _humidController = TextEditingController();
  final _windController = TextEditingController();
  final _remarksController = TextEditingController();

  // In a real app, this might come from settings
  final String _stationId = "STATION-001";

  @override
  void dispose() {
    _tempController.dispose();
    _rainController.dispose();
    _humidController.dispose();
    _windController.dispose();
    _remarksController.dispose();
    super.dispose();
  }

  void _submitForm() {
    if (_formKey.currentState!.validate()) {
      final observation = WeatherObservation(
        // id will be generated by DB
        stationId: _stationId,
        timestamp: DateTime.now(),
        temperature: double.tryParse(_tempController.text),
        rainfall: double.tryParse(_rainController.text),
        humidity: double.tryParse(_humidController.text),
        windSpeed: double.tryParse(_windController.text),
        remarks: _remarksController.text,
      );

      context.read<WeatherEntryBloc>().add(SaveObservationEvent(observation));
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('MeteoFow Collector'),
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
      ),
      body: BlocListener<WeatherEntryBloc, WeatherEntryState>(
        listener: (context, state) {
          if (state is WeatherEntrySuccess) {
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(content: Text('Observation Saved Successfully!')),
            );
            _formKey.currentState!.reset();
            _tempController.clear();
            _rainController.clear();
            _humidController.clear();
            _windController.clear();
            _remarksController.clear();
          } else if (state is WeatherEntryFailure) {
            ScaffoldMessenger.of(
              context,
            ).showSnackBar(SnackBar(content: Text(state.message)));
          }
        },
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(16.0),
          child: Form(
            key: _formKey,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                Card(
                  child: Padding(
                    padding: const EdgeInsets.all(16.0),
                    child: Column(
                      children: [
                        Text(
                          "Station: $_stationId",
                          style: Theme.of(context).textTheme.titleMedium,
                        ),
                        const SizedBox(height: 8),
                        Text(DateTime.now().toString().split('.')[0]),
                      ],
                    ),
                  ),
                ),
                const SizedBox(height: 16),
                TextFormField(
                  controller: _tempController,
                  decoration: const InputDecoration(
                    labelText: 'Temperature (°C)',
                    border: OutlineInputBorder(),
                  ),
                  keyboardType: const TextInputType.numberWithOptions(
                    decimal: true,
                    signed: true,
                  ),
                  validator: (value) {
                    if (value == null || value.isEmpty) {
                      return 'Please enter temperature';
                    }
                    final n = double.tryParse(value);
                    if (n == null) return 'Invalid number';
                    if (n < -50 || n > 60) {
                      return 'Value out of range (-50 to 60)';
                    }
                    return null;
                  },
                ),
                const SizedBox(height: 16),
                TextFormField(
                  controller: _rainController,
                  decoration: const InputDecoration(
                    labelText: 'Rainfall (mm)',
                    border: OutlineInputBorder(),
                  ),
                  keyboardType: const TextInputType.numberWithOptions(
                    decimal: true,
                  ),
                  validator: (value) {
                    if (value == null || value.isEmpty) {
                      return 'Please enter rainfall';
                    }
                    final n = double.tryParse(value);
                    if (n == null || n < 0) return 'Invalid rainfall';
                    return null;
                  },
                ),
                const SizedBox(height: 16),
                TextFormField(
                  controller: _humidController,
                  decoration: const InputDecoration(
                    labelText: 'Humidity (%)',
                    border: OutlineInputBorder(),
                  ),
                  keyboardType: const TextInputType.numberWithOptions(
                    decimal: true,
                  ),
                  validator: (value) {
                    if (value != null && value.isNotEmpty) {
                      final n = double.tryParse(value);
                      if (n == null || n < 0 || n > 100) return '0-100 only';
                    }
                    return null;
                  },
                ),
                const SizedBox(height: 16),
                TextFormField(
                  controller: _windController,
                  decoration: const InputDecoration(
                    labelText: 'Wind Speed (m/s)',
                    border: OutlineInputBorder(),
                  ),
                  keyboardType: const TextInputType.numberWithOptions(
                    decimal: true,
                  ),
                ),
                const SizedBox(height: 16),
                TextFormField(
                  controller: _remarksController,
                  decoration: const InputDecoration(
                    labelText: 'Remarks',
                    border: OutlineInputBorder(),
                  ),
                  maxLines: 2,
                ),
                const SizedBox(height: 24),
                BlocBuilder<WeatherEntryBloc, WeatherEntryState>(
                  builder: (context, state) {
                    return FilledButton(
                      onPressed: state is WeatherEntryLoading
                          ? null
                          : _submitForm,
                      child: state is WeatherEntryLoading
                          ? const CircularProgressIndicator()
                          : const Text('SAVE OBSERVATION'),
                    );
                  },
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
